name: Build and Test
permissions:
  contents: read
on: 
  workflow_dispatch:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

    paths:
      - "src/Transmitly.Microsoft.Aspnet.Mvc/**"
jobs:
  build_test_deploy_channel_provider:
    uses: transmitly/transmitly/.github/workflows/release-channel-provider.yml@main
    with: 
      channelProviderName: Transmitly.Microsoft.Aspnet.Mvc
    secrets: inherit
      
